### ISSUE TITLE
Cargo compilation error (Linux)

### ISSUE THREAD

**Issue by menentek** [hrkfdn/ncspot#238]
Hi!

Have been trying to install ncspot on OpenSuse Tumbleweed (latest snapshot). Tried `cargo install --git` and `cargo install --locked`

`cargo install -f ncspot`
(...)

```
Compiling librespot-core v0.1.3
 Compiling librespot-metadata v0.1.3
 Compiling librespot-audio v0.1.3
 Compiling librespot-playback v0.1.3
 Compiling rspotify v0.10.0
 Compiling ncspot v0.2.0
error[E0599]: no method named 'compat' found for type 'u64' in the current scope
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.2.0/src/spotify.rs:166:85
    |
166 | ...                   self.play_task = Box::pin(self.player.load(id, true, 0).compat());
    |                                                                               ^^^^^^ method not found in 'u64'
    |
    = note: the method 'compat' exists but the following trait bounds were not satisfied:
            'u64: futures::future::Future'
            which is required by 'u64: futures::compat::Future01CompatExt'
            'u64: futures::stream::Stream'
            which is required by 'u64: futures::compat::Stream01CompatExt'
            '&u64: futures::future::Future'
            which is required by '&u64: futures::compat::Future01CompatExt'
            '&u64: futures::stream::Stream'
            which is required by '&u64: futures::compat::Stream01CompatExt'
            '&mut u64: futures::future::Future'
            which is required by '&mut u64: futures::compat::Future01CompatExt'
            '&mut u64: futures::stream::Stream'
            which is required by '&mut u64: futures::compat::Stream01CompatExt'

error[E0063]: missing field 'gapless' in initializer of 'librespot_playback::config::PlayerConfig'
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ncspot-0.2.0/src/spotify.rs:408:29
    |
408 |         let player_config = PlayerConfig {
    |                             ^^^^^^^^^^^^ missing 'gapless'

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0063, E0599.
For more information about an error, try 'rustc --explain E0063'.
error: failed to compile 'ncspot v0.2.0', intermediate artifacts can be found at '/tmp/cargo-installMHjEpN'

Caused by:
  could not compile 'ncspot'.'
```

**Comment by guillaumedavidphd** [comment]
This is closed without an answer, @menentek how did you solve the problem? I'm running into the same issue trying to compile on Linux for raspberrypi 5.4.51+ armv6l.
Would love to learn about how to fix this.

**Comment by PsypherPunk** [comment]
@guillaumedavidphd, I ran into the same error (on Ubuntu 18.04 so I don't think it's Pi-specific.) However, after pulling the repo. and running `cargo build --release` (rather than a `cargo install`) it built fine. I presume whatever the underlying issue is has been fixed in a recent change on the main branch.
