### ISSUE TITLE
Doesn't compile with rust 1.32 (which is still the latest on the most distros)

### ISSUE THREAD

**Issue by im-n1** [hrkfdn/ncspot#33]
```
~/w/ncspot » cargo build --release                                                                                      101 develop?
   Compiling libdbus-sys v0.1.5
   Compiling cursive v0.11.0
   Compiling dbus v0.6.4
   Compiling ncspot v0.1.0 (/home/n1/workspace/ncspot)
error[E0658]: use of unstable library feature 'duration_as_u128' (see issue #50202)
   --> src/mpris.rs:164:60
    |
164 |                 iter.append(spotify.get_current_progress().as_micros() as i64);
    |                                                            ^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `ncspot`.

To learn more, run the command again with --verbose.
```
